### PR TITLE
Added Powerline-naked theme

### PR DESCRIPTION
**Pull request by edubxb**
New theme available, Powerline-naked.

### CODE REVIEW

**Comment by nwinkler** [comment]
Do you have a screenshot? What's the difference to the other Powerline themes?

**Comment by edubxb** [comment]
Nothing special, the same features that the others Powerline themes, but a different design.

Screenshot:

https://www.dropbox.com/s/pfltunufghzvxu6/bash_it-powerline-naked-screenshot.png?dl=0

**Comment by edubxb** [comment]
Any comments about merge this PR?

**Comment by tswicegood** [comment]
Nice.  Looks good to me.  If you're comfortable with where it's at, please add a screenshot over to the wiki.

**Comment by edubxb** [comment]
Perfect.

**Pull request merged**
