### PR TITLE
Improved Powerline-multiline theme

### PR DESCRIPTION
**Pull request by edubxb**
- Added a clock
- Added the battery status
- Visual improvements

Screenshot→ http://imgur.com/e7kFyBQ

### CODE REVIEW

**Comment by edubxb** [comment]
Found some issues, so this PR is not ready to merge, I will fix it soon.

**Comment by edubxb** [comment]
Ready! (I hope :yum:)

@tswicegood can you check that works correctly on Mac? Thanks!

**Comment by tswicegood** [comment]
@edubxb been using this for a few days.  I'm seeing oddness with the conda environment prompt.  See how the name overlaps the `(c)` character?

default

Any ideas?

**Comment by edubxb** [comment]
Seems that the rendering of some UTF-8 glyphs in Mac is very different from Linux, or probably, very dependant to the font, I use DejaVu Sans Mono, I checked it on the Mac of a friend (thanks @ifosch) who uses the Ubuntu Mono font and look weird too.

I updated the [screenshot](http://imgur.com/e7kFyBQ), so you can compare the rendering differences.

I will change it for a more convenient alternative, I personally prefer one character glyphs more than text labels to prevent the prompt becomes too wide.

The rest is working ok? Seems that the battery plugin don't work in Mavericks, can you check it or better, fix it? :smile:

**Comment by tswicegood** [comment]
Battery's working for me.  Let's merge -- I've been using it with no problems other than the font one and it's not really that annoying.

**Comment by tswicegood** [comment]
One thought -- maybe we should make all of those values default?  That way you can override it in your `.profile` or `.bashrc`.

**Comment by edubxb** [comment]
@tswicegood :ok_hand: for that, I will make these values changeable.

**Pull request merged**
