### PR TITLE
RVM prompt for powerline-multiline

### PR DESCRIPTION
**Pull request by ifosch**

### CODE REVIEW

**Comment by edubxb** [comment]
Looks good for me.

**Comment by tswicegood** [comment]
:+1: lgtm -- I don't have rvm locally to test, but if it works for you @ifosch, I'm happy to merge.

**Comment by ifosch** [comment]
Well, I've been using daily without a single problem.

**Comment by tswicegood** [comment]
Good enough for me.  Merging.  Thanks!!

**Pull request merged**
